// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwgeoppfxwwnluqxaboh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53Z2VvcHBmeHd3bmx1cXhhYm9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MjY5OTgsImV4cCI6MjA2NDIwMjk5OH0.rNxkRyPWexjzUCJJhWlaSw30tO96McrSYH-W5kqClGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);